name: CI Development
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install PNPM
        uses: pnpm/action-setup@v2
      - name: Setup node env
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          cache: 'pnpm'
          check-latest: true
          node-version: 'lts/*'
